### ISSUE TITLE
Gold Chain from Charm!

### ISSUE THREAD

**Issue by Kadynsr** [legoatoom/ConnectibleChains#30] opened 2022-10-06 18:48 UTC
I would love to be able to use this with the gold chains from charm!

**Comment by Kadynsr** [comment] 2022-10-09 20:29
I see that it's there in the code, and the ones in Dustrial Decor work but the ones in Charm don't?

**Comment by legoatoom** [comment] 2022-10-28 10:18
Duplicate of #26. I made a type in the code somewhere. Next update will resolve the issue.

**Closed by legoatoom** 2022-10-28 10:18 UTC
